version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000"
    networks:
      - gmfb
    deploy:
      mode: replicated
      replicas: 3  # Ensures 3 instances automatically
      restart_policy:
        condition: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBIT_MQ_URL=amqp://rabbitmq  # Connect to RabbitMQ instance

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    networks:
      - gmfb
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 10s
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq
      - RABBITMQ_ERLANG_COOKIE=secretcookie

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8000:8000"
    networks:
      - gmfb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

networks:
  gmfb:
    driver: bridge
