version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3  # Run 3 instances of the app
      restart_policy:
        condition: on-failure
    ports:
      - "8000"
    networks:
      - gmfb
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
    environment:
      - RABBIT_MQ_URL=amqp://rabbitmq1  # Update this based on your RabbitMQ setup

  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    ports:
      - "5672:5672"
      - "15673:15672"
    networks:
      - gmfb
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 10s
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=secretcookie  # Needed for clustering

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    networks:
      - gmfb
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      timeout: 10s
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
      - RABBITMQ_ERLANG_COOKIE=secretcookie  # Same cookie for clustering

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - gmfb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

networks:
  gmfb:
    name: gmfb
