name: Q-A-Api

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: stage

    strategy:
      matrix:
        node-version: [16.7]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd /home/ubuntu/gcmf-cib-api/ && sudo git stash && sudo git pull origin develop
    - run: sudo chmod -R 777 /home/ubuntu/gcmf-cib-api/
    - run: cd /home/ubuntu/gcmf-cib-api/ && npm ci
    - run: pm2 restart 1
    - run: sudo systemctl restart nginx
