name: Api

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: main

    strategy:
      matrix:
        node-version: [16.7]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd /home/ubuntu/gcmf-cib-api/ && sudo git stash && sudo git pull origin master
    - run: sudo chmod -R 777 /home/ubuntu/gcmf-cib-api/
    - run: cd /home/ubuntu/gcmf-cib-api/ && npm ci 
    - run: pm2 save --force  # Save the current process list to prevent missing IDs
    - run: pm2 resurrect     # Restore last saved state
    - run: pm2 restart all --update-env --time  # Ensure updated environment variables are used
    - run: sudo systemctl restart nginx

